### ISSUE TITLE
Publisher confirms support 

### ISSUE THREAD

**Issue by makasim** [makasim/amqpextra#3]

**Comment by makasim** [comment]
http://www.inanzzz.com/index.php/post/0aeg/creating-a-rabbitmq-producer-example-with-golang

**Comment by Crevil** [comment]
Do you have any plans of adding this functionality?

The recent rewrite have made the code a bit more manageable IMO so it might be possible to add this feature with some small tweaks to the `publisher. Publisher` and specifically add a channel read for confirmations in the `publish` method.

We (@lunarway) have recently adopted this library and are ready to help out if you need any help. :)

**Comment by makasim** [comment]
Yes, I am going to add it soon

**Comment by Crevil** [comment]
That sounds amazing 🎉 

As mentioned, let me know if you need any help now or in the future with this or the project in general. Thank you very much for your efforts so far 🙏
