### ISSUE TITLE
Add simple examples in readme

### ISSUE THREAD

**Issue by BarthV** [makasim/amqpextra#35]
It would be very nice to have some examples in the readme :
* how to initialize a resilient client
* simple publisher
* simple consumer
* (optional) complex publisher
* (optional) consumer with an exchange binding & emphemeral (auto-delete) queue

thanks !

**Comment by makasim** [comment]
We are working on go docs and examples are part of it. Something is already available https://pkg.go.dev/github.com/makasim/amqpextra

**Comment by BarthV** [comment]
:+1:

**Comment by makasim** [comment]
Added links to examples and doc to readme file
