### ISSUE TITLE
Questiong about handling queue deletion

### ISSUE THREAD

**Issue by neufeldtech** [makasim/amqpextra#5]
Hi @makasim,
Thanks for putting this library together, I hope to make use of it for building a robust consumer that can handle any variety of faults that may occur when my consumer is connected to a rabbitmq broker.

When playing with the example you've provided in https://github.com/makasim/amqpextra/blob/master/examples/conn_example.go I came across something that I wanted to run by you, to see if you have any input on how to best handle it.

I was running the example as-is, and was able to simulate a total network disruption (disconnected local machine from the network that the broker is on), and was able to to get it to reconnect as expected when the network was back online.

My next test involved deleting the queue (from the rabbitmq admin interface) while the consumer was listening. When I did this, I was receiving empty `amqp.Delivery` structs messages from the `msgCh` and my machine was consuming a lot of CPU because it's attempting to process these 'messages' as fast as it can.

Here we see the empty 'struct' that gets received  from the msgCh on a queue delete:
```
{Acknowledger:<nil> Headers:map[] ContentType: ContentEncoding: DeliveryMode:0 Priority:0 CorrelationId: ReplyTo: Expiration: MessageId: Timestamp:0001-01-01 00:00:00 +0000 UTC Type: UserId: AppId: ConsumerTag: MessageCount:0 DeliveryTag:0 Redelivered:false Exchange: RoutingKey: Body:[]}
```

To try to combat this issue and avoid sending the program into a loop that it can't recover from, one option is to examine the msg body and consumer tag that's coming in, and break out of the for loop if we receive "empty structs":

```
    for {
      select {
      case msg := <-msgCh:
        if len(msg.Body) == 0 && msg.ConsumerTag == "" {
          // Queue was deleted while consumer was connected...
          log.Printf("Received a suspect message... Redeclaring queues...")
          fmt.Printf("%+v\n", msg)
          continue L1
        } else {
          // process message here
          fmt.Printf("%+v\n", msg)
          log.Printf(string(msg.Body))
          msg.Ack(false)
        }
      case err, ok := <-closeCh:
        if !ok {
          log.Printf("amqp: consumption stopped")

          continue L1
        }

        log.Printf("amqp: consumption stopped: %v", err)

        continue L1
      }
    }
```

By adopting the labels pattern that is already in the example, we can achieve re-declaring our queue that got deleted from the admin interface, and the program is able to 'auto-recover'.

My question is around the detection of this condition - Is there a more go-idiomatic way of detecting when the queue gets deleted and we start reading empty structs from the msgCh? Checking the Body and other fields of the `msg` for "empty" values feels like a hack...

Any assistance or input you can provide would be appreciated. 

Thanks

**Comment by makasim** [comment]
> My next test involved deleting the queue (from the rabbitmq admin interface) while the consumer was listening. 

I've never tried that scenario. I guess that msgCh is closed, so instead of dealing with an empty struct, we should check for the second channel close arg.

**Comment by makasim** [comment]
Anyway I am going to explore that scenario. I'll let you know if I find something.

**Comment by neufeldtech** [comment]
Thanks very much for your quick response, the issue was that the channel was closed.

I've updated my example code the following and it behaves as expected.
```
      case msg, ok := <-msgCh:
        if !ok {
          fmt.Println("Consumption Channel is closed... attempting to redeclare amqp topology")
          continue L1
        }
        fmt.Printf("%+v\n", msg)
        log.Printf(string(msg.Body))
        msg.Ack(false)
```
