### ISSUE TITLE
WithRetryPeriod overload to enable custom retry strategies

### ISSUE THREAD

**Issue by mahlunar** [makasim/amqpextra#62]
**Background**
When services loose their connection, they will retry using some constant time.duration which might lead to a thundering herd if there are enough services that retry at the same time.
It can to some extend be mitigated by introducing a random jitter, but strategies like exponential backoff could also be relevant

**Current API limitations**
In the place where I work we are using the function:
```go
func WithRetryPeriod(dur time.Duration) Option
```

which only allows us to set a jitter. We see benefits in using an exponential backoff strategy instead.

**Proposal**
Would it be possible to get an overload like the following:
```go
func WithRetryPeriodFunc(timeFunc func(retryCount int) dur time.Duration) Option
```

That would make it possible for us to choose our own retry strategy, without adding the specific strategy to amqpextra.

I will be happy to give the implementation a go

**Comment by Crevil** [comment]
Just adding a couple of thoughts on this.

It could be a possibility to change the existing `WithRetryPeriod` instead of adding a new one if we can accept the breaking change. The existing behaviour can then be configured like this.

```diff
amqpextra.NewDialer(
-  amqpextra.WithRetryPeriod(1 * time.Second),
+  amqpextra.WithRetryPeriod(func(_ int) time.Duration { return 1*time.Second }),
)
```

Otherwise the existing option `WithRetryPeriod` could reuse this new option like this.

```go
func WithRetryPeriod(dur time.Duration) Option {
  return WithRetryPeriodFunc(func(_ int) time.Duration {
    return dur
  })
)
```

**Comment by makasim** [comment]
Looks good to me. I an up for non breaking change. WithRetryPeriod can use new func under the hood.

**Comment by mahlunar** [comment]
Great. I have assigned myself and will give it a go 👌🏼

**Comment by makasim** [comment]
I think we should pass a retry number to the function as well. To detect cases like lost conn -> connected -> lost conn again.
